### PR TITLE
Stupid mac tricks: Sed has different syntax on a mac and should be replaced with Perl

### PR DESCRIPTION
**Pull request by noahwsmith**
Addresses #115 - fixes sed for mac. Tested on linux and it still works fine over there, and on mac to ensure `make dev` completes.

### CODE REVIEW

**Comment by noahwsmith** [comment]
Ok, I've moved it to Perl from Sed. @dannylamb check me that I'm doing what you intended? I think I got it all working properly.

**Review by birkland — DISMISSED** [review]
I’m not at my machine right now, but I believe Perl would need to be installed explicitly if building on Windows in some circumstances.  So could you add Perl to the list of requirements in the README too?

**Comment by noahwsmith** [comment]
@birkland I make a small change to the Readme to address your request

**Review by seth-shaw-unlv — APPROVED** [review]
Works as advertised on my iMac.

**Comment by seth-shaw-unlv** [comment]
Anyone else want to give it a try before we merge this?

**Comment by rosiel** [comment]
I'm running it now... :D so far so good

**Review by rosiel — APPROVED** [review]
Yes! this worked!

**Pull request merged**
