### PR TITLE
Remove deprecated gateway external name

### PR DESCRIPTION
**Pull request by DonRichards**
### Fix warnings

Screen Shot 2021-10-11 at 11 14 22 AM

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Can we get testing instructions to reproduce the issue and then demonstrate the fix? Thanks.

**Comment by DonRichards** [comment]
@seth-shaw-unlv Just run `make demo` or some anything to bring it up. The warning should come up. I got this warning on both Linux and MAC. The error is part of the fresh build process. Perhaps run `make clean` first.

**Comment by DonRichards** [comment]
Just noticed another ticket has the warning within the output example. Although his ticket is referencing a composer version issue, it does show the warning messages I posted here. Not completely related but it shows the issue arises when the build process is fired (make local|demo).

https://github.com/Islandora-Devops/isle-dc/issues/184

**Comment by nigelgbanks** [comment]
Looks like the format has [changed](https://docs.docker.com/compose/networking/#use-a-pre-existing-network) so we should, set `external: true` like so:

```yml
gateway:
  external: true
  name: gateway
```

Our current method was deprecated in `version: "3.5"`. In all our `docker-compose` files we have  `version: "3.7"`

It looks like `external: true` must be [specified](https://docs.docker.com/compose/compose-file/compose-file-v3/#external-1) for it to work as it was previously.

**Comment by nigelgbanks** [comment]
Looks like we don't need to specify name either if it matches the same as the network configuration. 

```bash
docker network ls                          Sun 17 Oct 2021 12:54:49 UTC
NETWORK ID     NAME              DRIVER    SCOPE
eb0abd23fac3   bridge            bridge    local
1df64990806d   host              host      local
4943545796cd   isle-buildkit     bridge    local
225f8df1f00d   isle-dc_default   bridge    local
85f08ed21a62   isle-dc_gateway   bridge    local
e540e0060f15   none              null      local
```

So the following would be fine.

```yml
gateway:
  external: true
```

Here we can see that Alpaca is only on the default internal network as is expected and Drupal is on both.

```bash
docker inspect isle-dc_alpaca_1 | jq '.[].NetworkSettings.Networks | keys[]'
"isle-dc_default"
```

```bash
docker inspect isle-dc_drupal_1 | jq '.[].NetworkSettings.Networks | keys[]'
"isle-dc_default"
"isle-dc_gateway
```

**Review by nigelgbanks — APPROVED** [review]
I've made the changes I've recommend and tested it locally see the previous comment for the output.

**Comment by nigelgbanks** [comment]
@DonRichards if you're happy with my changes I'll go ahead and merge it.

**Pull request merged**
