### PR TITLE
Update traefik version

### PR DESCRIPTION
**Pull request by joshdentremont**
updated version of Traefik to match the version that site template uses.

### CODE REVIEW

**Review by joecorall — APPROVED** [review]
[LGTM](https://github.com/Islandora-Devops/isle-site-template/blob/afa3e82d7fec510c31f17c5788e024ce8c087cc9/docker-compose.yml#L595)

**Review by aOelschlager — APPROVED** [review]
LGTM too

**Comment by g7morris** [comment]
Quick question of why aren't we attempting to use the latest version of traefik of [2.10.4](https://github.com/traefik/traefik/releases) ? Did someone test and that didn't work?

Or does this traefik [value](https://github.com/Islandora-Devops/isle-site-template/blob/afa3e82d7fec510c31f17c5788e024ce8c087cc9/docker-compose.yml#L595) in the isle-site-template also need to be upgraded first and then this project? 

Just curious what the order of ops is here?

Should we work with @nigelgbanks on this too?

**Comment by g7morris** [comment]
Just an FYI, tested running with latest `2.10.4` on an existing site with no ill effects. More extensive testing warranted.

**Comment by joshdentremont** [comment]
@g7morris That's a good question. I just used the same one as the site template because I figured that was what was tested with Buildkit. 

I would be happy to bump it up, but I think we should probably keep Isle and Site Template on the same version, so we should bump both at the same time.

**Comment by nigelgbanks** [comment]
No need to sync with `isle-site-template`. The version used in the site template was just the latest available at the time it was written, I think. There isn't any real need to test with `isle-buildkit` releases, either. The only concern with `traefik` is the Docker labels used in the docker-compose.yml files. Since `isle-site-template` and `isle-dc` have different docker-compose.yml files, there isn't any need to keep them in sync.

**Comment by joshdentremont** [comment]
Updated this to use the newest version, 2.10.5

**Pull request merged**
