### PR TITLE
Add a default restart policy that can be changed

### PR DESCRIPTION
**Pull request by misilot**
Resolves Issue #172

I think I got all the files that would need to be changed.

### CODE REVIEW

**Comment by noahwsmith** [comment]
This looks beautiful to me. @nigelgbanks / @dannylamb any objections to merging this?

**Review by nigelgbanks — APPROVED** [review]

**Comment by nigelgbanks** [comment]
Looks solid, existing users will get an error as there is no default value in the `*.yml` files. Though I don't think it's too much burden for them to check and update their `.env` when they pull to the latest and compare it against the `sample.env`.

**Comment by misilot** [comment]
@nigelgbanks I can update this was a default value. What do you want it to be?

**Comment by nigelgbanks** [comment]
@misilot it should match the same default as is used in `sample.env` for clarity's sake

**Comment by misilot** [comment]
I can do that. I had picked what made sense for me in there but wanted to make sure made sense. I could change the value when redoing this if it didn't make sense for the project.

**Comment by misilot** [comment]
@nigelgbanks a default value has been set

**Review by nigelgbanks — APPROVED** [review]

**Pull request merged**
