### PR TITLE
Create troubleshooting.md

### PR DESCRIPTION
**Pull request by bondjimbond**
@noahwsmith Let me know if this is the wrong location.

### CODE REVIEW

**Comment by noahwsmith** [comment]
There's a troubleshooting section in the main Readme.md file with a few items already. Seems like that's a better place? Or move those things in here, and let this be a whole file for troubleshooting tips?

**Comment by bondjimbond** [comment]
I think a separate doc just for troubleshooting (with a reference to it in README.md so it can be easily found) is good

**Comment by bondjimbond** [comment]
OK, some updates to README.md and troubleshooting.md to reflect the above.

**Comment by noahwsmith** [comment]
I support this approach. @dannylamb and @nigelgbanks  - any thoughts?

**Review by nigelgbanks — APPROVED** [review]

**Pull request merged**
