### PR TITLE
Add simple way to update Drupal's admin password

### PR DESCRIPTION
**Pull request by DonRichards**
To make it easier to reset admin password this make command keeps it simple. 

To test use the readme instructions at the bottom of the "Secrets" section.

I tested this on mac and linux so it should work for either.

### CODE REVIEW

**Comment by DonRichards** [comment]
Will be adding another step. During the Tech call it was requested to pipe the password into the secrets file. I'll add this to this Pull request.

**Comment by DonRichards** [comment]
OK, ready for testing. Super simple low hanging fruit

**Comment by noahwsmith** [comment]
Running this off a `make clean` and `make local` gives

```
noah@bds76spare:~/Code/isle-dc$ make set_admin_password 
Password: 

Setting admin password now
 [success] Changed password for admin.
/bin/sh: 1: cannot create secrets/live/DRUPAL_DEFAULT_ACCOUNT_PASSWORD: Permission denied
make: *** [Makefile:365: set_admin_password] Error 2
```

I dealt with this in the `install-profile` branch to set ownership of /secrets/live when they are created. I'll add a new commit to bring that into this MR.

**Comment by noahwsmith** [comment]
Ok, this tests out fully for me. PWD is set in Drupal, I can log in, and the contents of that secret file is correct after the command runs. I'm happy to merge this unless someone else wants to test it first...

**Comment by DonRichards** [comment]
Thanks for reviewing

**Comment by DonRichards** [comment]
@Islandora-Devops/committers are we good with merging this?

**Comment by seth-shaw-unlv** [comment]
@DonRichards, please resolve conflicts.

**Comment by DonRichards** [comment]
@seth-shaw-unlv Not sure why it thought there was a conflict but either way it's resolved now.

**Comment by seth-shaw-unlv** [comment]
It worked to change the Drupal password but failed to update the live secrets file:
```
~/isle-dc$ make set_admin_password
Password:

Setting admin password now
 [success] Changed password for admin.
/bin/sh: 1: cannot create secrets/live/DRUPAL_DEFAULT_ACCOUNT_PASSWORD: Permission denied
make: *** [Makefile:394: set_admin_password] Error 2
```
Are we expected to run the make command as root?

**Comment by DonRichards** [comment]
OH!!! That's what you meant. No that isn't expected.

**Review by seth-shaw-unlv — APPROVED** [review]
🚀

**Comment by DonRichards** [comment]
@seth-shaw-unlv Got it!! Man that took too long. I added a check that basically looks to see if the Makefile/USER can write to the password file. If not it tries running the echo $password with sudo, otherwise it just echos the password to the file. This seems like the most reasonable approach.

**Comment by DonRichards** [comment]
Oh, great! Thanks

**Pull request merged**
