### PR TITLE
Test for create_database being called before the container has initia…

### PR DESCRIPTION
**Pull request by nigelgbanks**
…lized

### CODE REVIEW

**Comment by DonRichards** [comment]
Worked for me!

**Comment by misilot** [comment]
Works for me as well!

**Comment by misilot** [comment]
This Fixes #224

**Comment by g7morris** [comment]
@nigelgbanks How do you recommend testing here? What is the recommended process you used to build from scratch while checked out on this feature branch? 

Just want to be sure I've not missed any implicit steps. Perhaps @DonRichards and/or @misilot could share steps please?

**Comment by g7morris** [comment]
@nigelgbanks Tested this feature branch by doing the following:

* `git clone -b issues-224 git@github.com:Islandora-Devops/isle-dc.git`
* `cd isle-dc`
* `make demo`
  * output attached as a markdown file, 
[make_demo_output.md](https://github.com/Islandora-Devops/isle-dc/files/8044348/make_demo_output.md)
* Navigated to https://islandora.traefik.me and logged in.
* Site works!

Not sure if you needed any other information per the review but seems okay to me! Thanks

**Comment by misilot** [comment]
@g7morris sorry missed your requested, but you came up with what I had done.

**Pull request merged**
