### PR TITLE
Make local from demo

### PR DESCRIPTION
**Pull request by dannylamb**
Adding back in old "make dev" functionality to give folks the demo box as a 'local' install.

### CODE REVIEW

**Comment by misilot** [comment]
Thanks for putting this up @dannylamb 

Working through this I am getting the following error when running `make local-from-demo` and on the  `   $(MAKE) update-settings-php ENVIROMENT=demo` step from the call to the demo task.

```
Starting ksul-isle-dc_matomo_1  ... done
make[2]: Entering directory '/klib/app/isle-dc'
realpath: The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located./sites: No such file or directory
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
chmod: /settings.php: No such file or directory
make[2]: *** [Makefile:128: update-settings-php] Error 1
make[2]: Leaving directory '/klib/app/isle-dc'
make[1]: *** [Makefile:327: demo] Error 2
make[1]: Leaving directory '/klib/app/isle-dc'
make: *** [Makefile:359: local-from-demo] Error 2
```


However if I run ```make demo``` it seems to build correctly as expected.


UPDATE 4/26/2021:

So I believe this is related to `USE_SECRETS=true` and trying to set `ENVIRONMENT=local` if I don't touch those settings it seems to build correctly.

**Comment by dannylamb** [comment]
Thanks for this @misilot , I'll circle back soon and investigate.

**Comment by mdlincoln** [comment]
This is an extremely useful task for us to be able to run. Our use case: we want to generate a codebase folder with all of the latest islandora_defaults (with taxonomy definitions, Islandora Models content, etc.) fully installed, and use that as a foundation for further development.

During the 2021-05-25 Open Meeting, @dannylamb did a walk-through of the `local-from-demo` task, and we isolated an issue where the codebase downloaded from the task was outdated and didn't include a number of taxonomy definitions currently in islandora_defaults (re: https://github.com/Islandora/documentation/issues/1818) After some investigation, we found that this task skipped over enabling islandora_defaults, thus the `hydrate` task never imported the config from it b/c there was already existing config in the codebase.

Proposed solution was to add some kind of flag/logic that lets the user state whether or not they want to force an install of cmu_defaults.

**Comment by dannylamb** [comment]
@misilot Would you mind giving this another go?  I've made some changes and have managed to get this working for @mdlincoln , @hachacha and @bondjimbond.

Curious to see if it works for  you as well.  Thanks for being patient with us while we sort this out.

**Comment by dannylamb** [comment]
@mdlincoln I just pushed up a toggle for enabling islandora defaults when you run `make local`.  In your .env file, set `ENABLE_ISLANDORA_DEFAULTS` to control the behaviour (defaults to 'true').

**Comment by misilot** [comment]
@dannylamb 

```
grep: /var/www/drupal/web/sites/default/settings.php: No such file or directory

In Filesystem.php line 202:

  Failed to chmod file "/var/www/drupal/web/sites/default/settings.php".


islandora:settings:set-hash-salt [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify [NOTIFY]] [--druplicon] [--] <command> <salt>


In Filesystem.php line 202:

  Failed to chmod file "/var/www/drupal/web/sites/default/settings.php".


islandora:settings:set-flystem-fedora-url [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify [NOTIFY]] [--druplicon] [--] <command> <url>

PHP Notice:  Uninitialized string offset: 0 in /var/www/drupal/vendor/drush/drush/src/Preflight/ArgsPreprocessor.php on line 72
make[2]: *** [Makefile:128: update-settings-php] Error 129
make[2]: Leaving directory '/klib/app/isle-dc'
make[1]: *** [Makefile:327: demo] Error 2
make[1]: Leaving directory '/klib/app/isle-dc'
make: *** [Makefile:359: local-from-demo] Error 2


```

When running `make local-from-demo`

**Comment by noahwsmith** [comment]
This is super duper obsolete

**Pull request closed without merging**
